### ISSUE TITLE
API Interface 구성하기

### ISSUE THREAD

**Issue by SeonHyungJo** [Im-D/your-voice-back#6]
새로 만들어지는 API Response, Request가 필요합니다.

- 형식에 맞춘 값을 넣었을 경우 동일한 Request 보내기
- 형식에 맞지 않을 경우 에러 내려주기

크게 2가지 정도만 되면 될 거 같습니다.

**Comment by Dae-Hwa** [comment]
- Date : ISO 포멧(날짜-시간 사이 공백 대신 T)
- data 포멧 그대로(플랫하게)
- fail시 리퀘스트 데이터 그대로 리턴
